language: rust
rust:
  - 1.9.0
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly
before_install:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          sudo sh -c "add-apt-repository -y ppa:ubuntu-toolchain-r/test";
          sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main' >> /etc/apt/sources.list";
          wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -;
      fi
install:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          sudo apt-get update -qq;
          sudo apt-get install -qq llvm-3.6 libllvm3.6 libllvm3.6-dbg cmake libedit-dev;
          export PATH="/usr/lib/llvm-3.6/bin:$PATH";
      fi
  - |
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          brew update;
          brew rm -f llvm && brew install llvm;
          export LDFLAGS="-L/usr/local/opt/llvm/lib $LDFLAGS";
          export CPPFLAGS="-I/usr/local/opt/llvm/include $CPPFLAGS";
          export PATH="/usr/local/opt/llvm/bin:$PATH";
      fi
